### ISSUE TITLE
Error: Transaction wasn't processed in 240 seconds

### ISSUE THREAD

**Issue by JasonHsu1018** [gongbell/ContractFuzzer#13]
I've just run ContractFuzzer on the examples you provided under the `examples/exception_disorder` diretory. But the fuzzing results showed no "exception disorder" in the six tested contracts. When I opened the file `tester_run.log `, I noticed this kind of error occured a lot:
```
Error: Transaction 0xd4fb032cacfa0e8648f48a60fa750c8f62bbe19f31214765067ddb5fb8b39ed8 wasn't processed in 240 seconds
    at Object.callback (/ContractFuzzer/contract_tester/node_modules/truffle-contract/contract.js:177:35)            
    at /ContractFuzzer/contract_tester/node_modules/web3/lib/web3/method.js:142:25                                   
    at /ContractFuzzer/contract_tester/node_modules/web3/lib/web3/requestmanager.js:89:9                             
    at XMLHttpRequest.request.onreadystatechange (/ContractFuzzer/contract_tester/node_modules/web3/lib/web3/httpprov
    at XMLHttpRequestEventTarget.dispatchEvent (/ContractFuzzer/contract_tester/node_modules/xhr2/lib/xhr2.js:64:18) 
    at XMLHttpRequest._setReadyState (/ContractFuzzer/contract_tester/node_modules/xhr2/lib/xhr2.js:354:12)          
    at XMLHttpRequest._onHttpResponseEnd (/ContractFuzzer/contract_tester/node_modules/xhr2/lib/xhr2.js:509:12)      
    at IncomingMessage.<anonymous> (/ContractFuzzer/contract_tester/node_modules/xhr2/lib/xhr2.js:469:24)            
    at IncomingMessage.emit (events.js:185:15)                                                                       
    at IncomingMessage.emit (domain.js:422:20)                                                                       
    at endReadableNT (_stream_readable.js:1106:12)                                                                   
    at process._tickCallback (internal/process/next_tick.js:178:19)   

```

And `count.txt` showed me that `HackerRootCallFailed` happened more than half of the time.
Are all these things normal? I really don't know what's going on here.

**Comment by sunbeam891** [comment]
Hi, were you able to fix this error? Even I am getting the same error of not being able to process in 240 seconds

**Comment by rajguru7** [comment]
Getting the same error. Were you able to figure out why?

**Comment by rajguru7** [comment]
The existing private blockchain has slowed down over time and now the mining speed is too low. truffle-contract is timing out while trying to push the transaction
